import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Loader2, LockKeyhole, Plus, SearchCheck, CircleHelp, FileText, Link2, Lightbulb, AlertTriangle } from "lucide-react";
import { toast } from "sonner";

const tabs = ["Overview", "Question", "Sources", "Evidence", "Claims", "Findings", "Unknowns", "Activity"] as const;
type Tab = typeof tabs[number];
const definitions: Record<string, string> = {
  FACT: "Directly established by the linked source-backed evidence in this record.",
  INFERENCE: "A reasoned interpretation drawn from evidence; it is not itself a direct fact.",
  CLAIM: "An assertion attributed to a person, organization, or source.",
  AUTHORITY: "A statement or determination whose authority comes from an identified institution or governing source.",
  CONTRADICTION: "Material evidence or assertions that conflict with another record element.",
  QUESTION: "An unresolved proposition that needs investigation.",
  UNKNOWN: "Something not established by the current record and deliberately left unresolved.",
};

function Category({ value }: { value: string }) { return <div title={definitions[value]}><Badge variant="outline">{value}</Badge></div>; }

export default function RecordWorkspace() {
  const { loading, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const [tab, setTab] = useState<Tab>("Overview");
  const [recordId, setRecordId] = useState<number | null>(null);
  const [showCreateRecord, setShowCreateRecord] = useState(false);
  const [showCreateSource, setShowCreateSource] = useState(false);
  const [showCreateEvidence, setShowCreateEvidence] = useState(false);
  const [showCreateClaim, setShowCreateClaim] = useState(false);
  const [showCreateFinding, setShowCreateFinding] = useState(false);
  const [showCreateUnknown, setShowCreateUnknown] = useState(false);
  const records = trpc.canonical.records.list.useQuery(undefined, { enabled: isAuthenticated });
  const selectedId = recordId ?? records.data?.[0]?.id ?? null;
  const record = trpc.canonical.records.get.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });
  const sources = trpc.canonical.sources.list.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });
  const evidence = trpc.canonical.evidence.list.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });
  const claims = trpc.canonical.claims.list.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });
  const findings = trpc.canonical.findings.list.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });
  const unknowns = trpc.canonical.unknowns.list.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });
  const audit = trpc.canonical.audit.list.useQuery({ recordId: selectedId ?? 0 }, { enabled: Boolean(selectedId && isAuthenticated) });

  const createRecord = trpc.canonical.records.create.useMutation({ onSuccess: async ({ id }) => { await utils.canonical.records.list.invalidate(); setRecordId(id); setShowCreateRecord(false); setTab("Question"); toast.success("Private record created."); } });
  const updateSource = trpc.canonical.sources.update.useMutation({ onSuccess: async () => { await sources.refetch(); toast.success("Source updated."); } });
  const updateEvidence = trpc.canonical.evidence.update.useMutation({ onSuccess: async () => { await evidence.refetch(); toast.success("Evidence updated."); } });
  const createSource = trpc.canonical.sources.create.useMutation({ onSuccess: async () => { await sources.refetch(); setShowCreateSource(false); setTab("Evidence"); toast.success("Source saved."); } });
  const createEvidence = trpc.canonical.evidence.create.useMutation({ onSuccess: async () => { await evidence.refetch(); setShowCreateEvidence(false); setTab("Claims"); toast.success("Source-backed evidence saved."); } });
  const createClaim = trpc.canonical.claims.create.useMutation({ onSuccess: async () => { await claims.refetch(); setShowCreateClaim(false); setTab("Findings"); toast.success("Claim saved as an assertion."); } });
  const createFinding = trpc.canonical.findings.create.useMutation({ onSuccess: async () => { await findings.refetch(); setShowCreateFinding(false); toast.success("Finding saved with its epistemic category."); }, onError: e => toast.error(e.message) });
  const createUnknown = trpc.canonical.unknowns.create.useMutation({ onSuccess: async () => { await unknowns.refetch(); setShowCreateUnknown(false); toast.success("Unknown preserved in the record."); } });

  if (loading) return <div className="grid min-h-screen place-items-center"><Loader2 className="h-7 w-7 animate-spin" /></div>;
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-stone-50 p-6"><Card className="max-w-lg"><CardHeader><CardTitle>Open the Record</CardTitle><CardDescription>This workspace is private. Sign in before accessing records.</CardDescription></CardHeader><CardContent><Button onClick={() => startLogin()}><LockKeyhole className="mr-2 h-4 w-4" />Sign in with Manus OAuth</Button></CardContent></Card></main>;

  const current = record.data;
  const selectedSources = sources.data ?? [];
  const selectedEvidence = evidence.data ?? [];
  const selectedClaims = claims.data ?? [];
  const selectedFindings = findings.data ?? [];
  const selectedUnknowns = unknowns.data ?? [];

  return <div className="min-h-screen bg-[#f7f6f1] text-stone-900">
    <header className="border-b bg-white px-5 py-4 lg:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-800">Open the Record</p><h1 className="mt-1 font-serif text-2xl">Question → Source → Evidence → Claim → Finding → Unknown</h1></div><Button onClick={() => setShowCreateRecord(true)}><Plus className="mr-2 h-4 w-4" />New record</Button></div></header>
    <main className="mx-auto max-w-7xl p-5 lg:p-10">
      <div className="grid gap-6 lg:grid-cols-[250px_1fr]">
        <aside className="space-y-3"><Card><CardHeader><CardTitle className="text-base">Private records</CardTitle></CardHeader><CardContent className="space-y-1">{(records.data ?? []).map(item => <button key={item.id} onClick={() => setRecordId(item.id)} className={`w-full rounded-lg p-3 text-left text-sm ${item.id === selectedId ? "bg-emerald-50 ring-1 ring-emerald-200" : "hover:bg-stone-50"}`}><div className="font-medium">{item.title}</div><div className="mt-1 text-xs text-stone-500">{item.status} · {item.visibility}</div></button>)}{!records.data?.length && <div className="rounded-lg border border-dashed p-4 text-sm text-stone-500">No records yet. Start with the question you are trying to establish.</div>}</CardContent></Card>{selectedId && <Card><CardHeader><CardTitle className="text-base">Epistemic guide</CardTitle></CardHeader><CardContent className="space-y-2 text-xs text-stone-600">{Object.entries(definitions).map(([key, value]) => <div key={key}><strong>{key}</strong> — {value}</div>)}</CardContent></Card>}</aside>
        <section className="space-y-5">{!selectedId || !current ? <Card><CardContent className="p-10 text-center text-stone-500">Create a private record to begin.</CardContent></Card> : <>
          <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="font-serif text-3xl">{current.title}</CardTitle><CardDescription className="mt-2">{current.description || "No context entered yet."}</CardDescription></div><Badge variant="outline">PRIVATE · {current.status}</Badge></div></CardHeader><CardContent><nav className="flex gap-1 overflow-x-auto border-t pt-3">{tabs.map(item => <Button key={item} size="sm" variant={tab === item ? "default" : "ghost"} onClick={() => setTab(item)}>{item}</Button>)}</nav></CardContent></Card>

          {tab === "Overview" && <div className="grid gap-4 md:grid-cols-3">{[["Sources", selectedSources.length, "Document the origin before interpreting it."],["Evidence", selectedEvidence.length, "Every item points to a source and locator where known."],["Unknowns", selectedUnknowns.filter(x => x.status !== "RESOLVED").length, "Keep unresolved gaps visible."]].map(([label, count, help]) => <Card key={String(label)}><CardHeader><CardTitle className="text-base">{label} <span className="float-right text-2xl">{String(count)}</span></CardTitle><CardDescription>{help}</CardDescription></CardHeader></Card>)}<Card className="md:col-span-3"><CardHeader><CardTitle>Traceability</CardTitle><CardDescription>A finding should be readable back to the claim, evidence, and originating source.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Badge>Question</Badge><span>→</span><Badge>Source</Badge><span>→</span><Badge>Evidence</Badge><span>→</span><Badge>Claim</Badge><span>→</span><Badge>Finding</Badge><span>→</span><Badge>Unknown</Badge></CardContent></Card></div>}

          {tab === "Question" && <Card><CardHeader><CardTitle>What are you trying to establish?</CardTitle><CardDescription>The original question is preserved verbatim. It is the starting point, not a conclusion.</CardDescription></CardHeader><CardContent><div className="rounded-xl border bg-stone-50 p-5 whitespace-pre-wrap">{current.originalQuestion || "No original question entered."}</div></CardContent></Card>}

          {tab === "Sources" && <ListSection title="Sources" action="Add source" onAction={() => setShowCreateSource(true)} icon={<FileText className="h-4 w-4" />}><div className="space-y-3">{selectedSources.map(source => <Card key={source.id}><CardContent className="p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{source.title}</p><p className="text-sm text-stone-600">{source.recordType} · {source.origin} · {source.location}</p></div><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={() => { const title = window.prompt("Source title", source.title); if (title) updateSource.mutate({ recordId: selectedId, sourceRecordId: source.id, title, sourceType: source.recordType, location: source.location, publisher: source.origin, publicationDate: source.documentDate, designation: source.canonical?.designation ?? "UNKNOWN", citationText: source.canonical?.citationText ?? "", notes: source.canonical?.notes ?? "" }); }}>Edit</Button><Badge variant="outline">{source.canonical?.designation ?? "UNKNOWN"}</Badge></div></div><p className="mt-3 text-sm text-stone-600">{source.canonical?.citationText || source.provenanceNote}</p></CardContent></Card>)}{!selectedSources.length && <Empty text="Add the source before adding evidence." />}</div></ListSection>}

          {tab === "Evidence" && <ListSection title="Source-backed evidence" action="Add evidence" onAction={() => setShowCreateEvidence(true)} icon={<SearchCheck className="h-4 w-4" />}><div className="space-y-3">{selectedEvidence.map(item => <Card key={item.id}><CardContent className="p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold">{item.label}</p><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={() => { const excerpt = window.prompt("Evidence excerpt", item.excerptText); if (excerpt) updateEvidence.mutate({ recordId: selectedId, evidenceId: item.id, title: item.label, excerpt, locator: item.locator, confidenceStatus: item.confidenceStatus, notes: item.notes }); }}>Edit</Button><Badge variant="outline">{item.confidenceStatus}</Badge></div></div><blockquote className="mt-3 border-l-2 pl-4 text-sm whitespace-pre-wrap">{item.excerptText}</blockquote><p className="mt-3 text-xs text-stone-500">Source #{item.sourceRecordId}{item.locator ? ` · Locator: ${item.locator}` : " · Locator not supplied"}</p>{item.notes && <p className="mt-2 text-sm text-stone-600">Notes: {item.notes}</p>}</CardContent></Card>)}{!selectedEvidence.length && <Empty text="Evidence is an exact excerpt or observation tied to a source—not a vague statement that something proves a conclusion." />}</div></ListSection>}

          {tab === "Claims" && <ListSection title="Claims" action="Add claim" onAction={() => setShowCreateClaim(true)} icon={<Link2 className="h-4 w-4" />}><div className="space-y-3">{selectedClaims.map(item => <Card key={item.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{item.claimText}</p><Category value="CLAIM" /></div><p className="mt-2 text-sm text-stone-600">{item.claimant ? `Attributed to ${item.claimant}. ` : "Attribution not recorded. "}{item.notes}</p></CardContent></Card>)}{!selectedClaims.length && <Empty text="A claim is an assertion. Enter it without upgrading it to fact." />}</div></ListSection>}

          {tab === "Findings" && <ListSection title="Findings" action="Add finding" onAction={() => setShowCreateFinding(true)} icon={<Lightbulb className="h-4 w-4" />}><div className="space-y-3">{selectedFindings.map(item => <Card key={item.id}><CardContent className="p-4"><div className="flex flex-wrap justify-between gap-3"><p className="font-semibold">{item.findingText}</p><Category value={item.epistemicCategory} /></div><p className="mt-3 text-sm"><strong>Rationale:</strong> {item.rationale}</p>{item.missingEvidence && <p className="mt-2 text-sm text-stone-600"><strong>Missing evidence:</strong> {item.missingEvidence}</p>}<p className="mt-2 text-xs text-stone-500">{item.epistemicCategory === "FACT" ? "FACT requires linked supporting evidence." : "Inference remains an interpretation, not a direct fact."}</p></CardContent></Card>)}{!selectedFindings.length && <Empty text="A finding states what the linked record supports. Choose FACT only when source-backed evidence is linked." />}</div></ListSection>}

          {tab === "Activity" && <ListSection title="Activity / Audit History" action="" onAction={() => undefined} icon={<CircleHelp className="h-4 w-4" />}><div className="space-y-2">{(audit.data ?? []).map(item => <div key={item.id} className="rounded-lg border bg-white p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{item.action}</strong><span className="text-xs text-stone-500">{item.entityType} #{item.entityId} · {new Date(item.occurredAt).toLocaleString()}</span></div><p className="mt-1 text-stone-600">{item.summary}</p></div>)}{!audit.data?.length && <Empty text="No canonical audit events yet." />}</div></ListSection>}

          {tab === "Unknowns" && <ListSection title="Unknowns / unresolved questions" action="Add unknown" onAction={() => setShowCreateUnknown(true)} icon={<CircleHelp className="h-4 w-4" />}><div className="space-y-3">{selectedUnknowns.map(item => <Card key={item.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{item.description}</p><Badge variant="outline">{item.status}</Badge></div><p className="mt-2 text-sm text-stone-600">Why it matters: {item.whyItMatters}</p>{item.resolutionNotes && <p className="mt-2 text-sm">Resolution: {item.resolutionNotes}</p>}</CardContent></Card>)}{!selectedUnknowns.length && <Empty text="Unknowns are deliberately preserved gaps. Adding a finding does not erase them." />}</div></ListSection>}
        </>}</section>
      </div>
    </main>

    {showCreateRecord && <Modal title="Create private record" onClose={() => setShowCreateRecord(false)}><form className="space-y-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); createRecord.mutate({ title: String(f.get("title") || ""), description: String(f.get("description") || ""), originalQuestion: String(f.get("question") || "") }); }}><Input name="title" placeholder="Record title" required /><Textarea name="description" placeholder="Context or description" /><Textarea name="question" placeholder="What are you trying to establish?" required /><Button type="submit" disabled={createRecord.isPending}>Create private record</Button></form></Modal>}
    {selectedId && showCreateSource && <Modal title="Add source" onClose={() => setShowCreateSource(false)}><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); createSource.mutate({ recordId: selectedId, title: String(f.get("title") || ""), sourceType: String(f.get("type") || ""), location: String(f.get("location") || ""), publisher: String(f.get("publisher") || ""), publicationDate: String(f.get("date") || "") || null, retrievalAt: null, designation: String(f.get("designation") || "UNKNOWN") as "PRIMARY" | "SECONDARY" | "UNKNOWN", citationText: String(f.get("citation") || ""), notes: String(f.get("notes") || "") }); }}><Input name="title" placeholder="Source title" required /><Input name="type" placeholder="Source type (court filing, report, interview...)" required /><Input name="publisher" placeholder="Publisher / author / agency" /><Input name="location" placeholder="URL or physical/location reference" required /><Input name="date" placeholder="Publication date (if known)" /><select name="designation" className="w-full rounded-md border p-2"><option>UNKNOWN</option><option>PRIMARY</option><option>SECONDARY</option></select><Textarea name="citation" placeholder="Citation/reference text" /><Textarea name="notes" placeholder="Notes / provenance" /><Button type="submit">Save source</Button></form></Modal>}
    {selectedId && showCreateEvidence && <Modal title="Add source-backed evidence" onClose={() => setShowCreateEvidence(false)}><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); createEvidence.mutate({ recordId: selectedId, sourceRecordId: Number(f.get("sourceId")), title: String(f.get("title") || ""), excerpt: String(f.get("excerpt") || ""), locator: String(f.get("locator") || "") || null, confidenceStatus: String(f.get("confidence") || "VERIFY") as any, notes: String(f.get("notes") || "") }); }}><select name="sourceId" required className="w-full rounded-md border p-2"><option value="">Select source</option>{selectedSources.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select><Input name="title" placeholder="Evidence title" required /><Textarea name="excerpt" placeholder="Exact excerpt, observation, or description" required /><Input name="locator" placeholder="Page, paragraph, timestamp, section, URL fragment, exhibit/item" /><select name="confidence" className="w-full rounded-md border p-2"><option>VERIFY</option><option>PRIMARY-RECORD</option><option>USER-REPORTED</option><option>SOURCE-UNAVAILABLE</option><option>CONFLICTING</option></select><Textarea name="notes" placeholder="Evidence notes" /><Button type="submit" disabled={!selectedSources.length}>Save evidence</Button></form></Modal>}
    {selectedId && showCreateClaim && <Modal title="Add claim" onClose={() => setShowCreateClaim(false)}><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); createClaim.mutate({ recordId: selectedId, claimText: String(f.get("text") || ""), claimant: String(f.get("claimant") || "") || null, claimDate: String(f.get("date") || "") || null, claimType: String(f.get("type") || "assertion"), notes: String(f.get("notes") || ""), supportingEvidenceIds: f.getAll("supportingEvidenceIds").map(Number), contraryEvidenceIds: f.getAll("contraryEvidenceIds").map(Number), sourceRecordIds: f.getAll("sourceRecordIds").map(Number) }); }}><Textarea name="text" placeholder="State the claim exactly as an assertion" required /><Input name="claimant" placeholder="Claimant / attributed speaker (optional)" /><Input name="date" placeholder="Claim date (optional)" /><Input name="type" placeholder="Claim type" defaultValue="assertion" /><Textarea name="notes" placeholder="Notes" /><label className="text-sm font-medium">Supporting evidence</label><select name="supportingEvidenceIds" multiple className="min-h-24 w-full rounded-md border p-2">{selectedEvidence.map(e => <option key={e.id} value={e.id}>{e.label}</option>)}</select><label className="text-sm font-medium">Contrary evidence</label><select name="contraryEvidenceIds" multiple className="min-h-24 w-full rounded-md border p-2">{selectedEvidence.map(e => <option key={e.id} value={e.id}>{e.label}</option>)}</select><label className="text-sm font-medium">Direct sources</label><select name="sourceRecordIds" multiple className="min-h-20 w-full rounded-md border p-2">{selectedSources.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select><p className="text-xs text-stone-500">This form creates a CLAIM, never a FACT. Supporting and contrary evidence are explicit links.</p><Button type="submit">Save claim</Button></form></Modal>}
    {selectedId && showCreateFinding && <Modal title="Add finding" onClose={() => setShowCreateFinding(false)}><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const supporting = f.getAll("supportingEvidenceIds").map(Number); createFinding.mutate({ recordId: selectedId, findingText: String(f.get("text") || ""), epistemicCategory: String(f.get("category") || "INFERENCE") as any, rationale: String(f.get("rationale") || ""), confidenceExplanation: String(f.get("confidence") || ""), alternativeExplanation: String(f.get("alternative") || ""), missingEvidence: String(f.get("missing") || ""), whatWouldChangeConclusion: String(f.get("change") || ""), supportingEvidenceIds: supporting, contraryEvidenceIds: f.getAll("contraryEvidenceIds").map(Number), claimIds: f.getAll("claimIds").map(Number) }); }}><Textarea name="text" placeholder="Finding" required /><select name="category" className="w-full rounded-md border p-2"><option>INFERENCE</option><option>FACT</option></select><Textarea name="rationale" placeholder="Explanation / rationale" required /><Textarea name="confidence" placeholder="Confidence explanation (separate from epistemic category)" /><Textarea name="alternative" placeholder="Alternative explanation" /><Textarea name="missing" placeholder="Missing evidence" /><Textarea name="change" placeholder="What would change this conclusion?" /><label className="text-sm font-medium">Supporting evidence</label><select name="supportingEvidenceIds" multiple className="min-h-24 w-full rounded-md border p-2">{selectedEvidence.map(e => <option key={e.id} value={e.id}>{e.label}</option>)}</select><label className="text-sm font-medium">Contrary evidence</label><select name="contraryEvidenceIds" multiple className="min-h-24 w-full rounded-md border p-2">{selectedEvidence.map(e => <option key={e.id} value={e.id}>{e.label}</option>)}</select><label className="text-sm font-medium">Related claims</label><select name="claimIds" multiple className="min-h-20 w-full rounded-md border p-2">{selectedClaims.map(c => <option key={c.id} value={c.id}>{c.claimText}</option>)}</select><p className="text-xs text-stone-500">FACT requires at least one supporting evidence item. INFERENCE may be used for reasoned interpretation.</p><Button type="submit" disabled={selectedEvidence.length === 0 && false}>Save finding</Button></form></Modal>}
    {selectedId && showCreateUnknown && <Modal title="Preserve an unknown" onClose={() => setShowCreateUnknown(false)}><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); createUnknown.mutate({ recordId: selectedId, description: String(f.get("description") || ""), whyItMatters: String(f.get("why") || ""), relatedClaimId: null, relatedFindingId: null, relatedSourceRecordId: null, relatedChronologyEventId: null }); }}><Textarea name="description" placeholder="What remains unknown or unresolved?" required /><Textarea name="why" placeholder="Why does this matter?" required /><Button type="submit">Save unknown</Button></form></Modal>}
  </div>;
}

function ListSection({ title, action, onAction, icon, children }: { title: string; action: string; onAction: () => void; icon: React.ReactNode; children: React.ReactNode }) { return <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2">{icon}{title}</CardTitle><CardDescription>Private to this record owner.</CardDescription></div><Button size="sm" onClick={onAction}><Plus className="mr-1 h-4 w-4" />{action}</Button></div></CardHeader><CardContent>{children}</CardContent></Card>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed p-6 text-sm text-stone-500"><AlertTriangle className="mb-2 h-4 w-4" />{text}</div>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><Card className="max-h-[90vh] w-full max-w-xl overflow-auto"><CardHeader><div className="flex items-center justify-between"><CardTitle>{title}</CardTitle><Button variant="ghost" onClick={onClose}>Close</Button></div></CardHeader><CardContent>{children}</CardContent></Card></div>; }
