import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { DisclosureBanner, colors } from "@/components/case-ui";
import { ScreenContainer } from "@/components/screen-container";
import { EvidenceStatus, RecordKind, TimePrecision, useCaseData } from "@/lib/case-store";

const kinds: RecordKind[] = ["SOURCE", "CLAIM", "QUESTION", "DATE", "MISSING_EVIDENCE", "CONTRADICTION", "PERSON", "AGENCY"];
const statuses: EvidenceStatus[] = ["PRIMARY_RECORD", "USER_REPORTED", "VERIFY", "SOURCE_UNAVAILABLE", "CONFLICTING"];
const timePrecisions: TimePrecision[] = ["EXACT", "APPROXIMATE", "RANGE", "CONFLICTING", "UNSPECIFIED"];

export default function AddRecordScreen() {
  const router = useRouter(); const { addRecord } = useCaseData();
  const [kind, setKind] = useState<RecordKind>("SOURCE"); const [status, setStatus] = useState<EvidenceStatus>("VERIFY"); const [timePrecision, setTimePrecision] = useState<TimePrecision>("UNSPECIFIED");
  const [itemName, setItemName] = useState(""); const [statement, setStatement] = useState(""); const [source, setSource] = useState(""); const [location, setLocation] = useState(""); const [incidentDate, setIncidentDate] = useState(""); const [createdDate, setCreatedDate] = useState(""); const [receivedDate, setReceivedDate] = useState(""); const [custodian, setCustodian] = useState(""); const [people, setPeople] = useState(""); const [passage, setPassage] = useState(""); const [chainOfCustody, setChainOfCustody] = useState(""); const [fileHash, setFileHash] = useState(""); const [reliabilityConcerns, setReliabilityConcerns] = useState(""); const [authenticationQuestions, setAuthenticationQuestions] = useState(""); const [potentialDiscrepancy, setPotentialDiscrepancy] = useState(""); const [nextAction, setNextAction] = useState("");
  function save() {
    if (!itemName.trim() || !statement.trim() || !source.trim()) { Alert.alert("Add an item name, statement, and source", "Use neutral wording and record where the item came from before saving it to the workspace."); return; }
    addRecord({ kind, status, itemName: itemName.trim(), statement: statement.trim(), source: source.trim(), location: location.trim(), date: incidentDate.trim(), incidentDate: incidentDate.trim(), createdDate: createdDate.trim(), receivedDate: receivedDate.trim(), custodian: custodian.trim() || "Not recorded", people: people.trim() || "Not recorded", relatedPeople: people.trim() ? people.split(",").map((entry) => entry.trim()).filter(Boolean) : [], passage: passage.trim() || "No passage or source summary recorded.", chainOfCustody: chainOfCustody.trim(), fileHash: fileHash.trim(), reliabilityConcerns: reliabilityConcerns.trim(), authenticationQuestions: authenticationQuestions.trim(), potentialDiscrepancy: potentialDiscrepancy.trim(), nextAction: nextAction.trim() || "Review the original source and identify the next verification step.", confidence: status === "PRIMARY_RECORD" ? "High" : status === "VERIFY" ? "Needs review" : "Unverified", appearsMissing: status === "SOURCE_UNAVAILABLE", timePrecision });
    router.back();
  }
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.container}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <TopBar title="New evidence item" onBack={() => router.back()} /><Text style={styles.title}>Capture the item and its provenance.</Text><Text style={styles.subtitle}>Missing facts and potential inconsistencies remain questions for review—not conclusions.</Text><DisclosureBanner compact />
    <FormLabel label="Item name" required /><TextInput value={itemName} onChangeText={setItemName} placeholder="Example: Officer narrative report" placeholderTextColor="#8B97A5" style={styles.input} returnKeyType="next" />
    <FormLabel label="Record category" /><Selector items={kinds} value={kind} onChange={setKind} />
    <FormLabel label="Verification status" /><Selector items={statuses} value={status} onChange={setStatus} />
    <FormLabel label="Neutral statement or question" required /><TextInput value={statement} onChangeText={setStatement} multiline placeholder="Example: The report lists an event time that should be compared with primary records." placeholderTextColor="#8B97A5" style={[styles.input, styles.textarea]} textAlignVertical="top" />
    <FormLabel label="Source name" required /><TextInput value={source} onChangeText={setSource} placeholder="Court filing, report, notice, recording index, or user note" placeholderTextColor="#8B97A5" style={styles.input} returnKeyType="next" />
    <FormLabel label="Location / citation" hint="Page, paragraph, entry, timestamp, URL, or file name" /><TextInput value={location} onChangeText={setLocation} placeholder="Example: Report page 2, paragraph 4" placeholderTextColor="#8B97A5" style={styles.input} returnKeyType="next" />
    <FormLabel label="Incident or record date" hint="YYYY-MM-DD when known" /><TextInput value={incidentDate} onChangeText={setIncidentDate} placeholder="YYYY-MM-DD" placeholderTextColor="#8B97A5" style={styles.input} autoCapitalize="none" returnKeyType="next" />
    <FormLabel label="Time precision" /><Selector items={timePrecisions} value={timePrecision} onChange={setTimePrecision} />
    <FormLabel label="Created and received dates" hint="Use YYYY-MM-DD where known" /><View style={styles.row}><TextInput value={createdDate} onChangeText={setCreatedDate} placeholder="Created" placeholderTextColor="#8B97A5" style={[styles.input, styles.half]} autoCapitalize="none" /><TextInput value={receivedDate} onChangeText={setReceivedDate} placeholder="Received" placeholderTextColor="#8B97A5" style={[styles.input, styles.half]} autoCapitalize="none" /></View>
    <FormLabel label="Custodian and related people" /><TextInput value={custodian} onChangeText={setCustodian} placeholder="Agency, court, person, or office holding the original" placeholderTextColor="#8B97A5" style={styles.input} /><TextInput value={people} onChangeText={setPeople} placeholder="Comma-separated names or roles, as recorded" placeholderTextColor="#8B97A5" style={styles.input} />
    <FormLabel label="Passage or source summary" /><TextInput value={passage} onChangeText={setPassage} multiline placeholder="Quote or summarize the relevant passage without changing what the source says." placeholderTextColor="#8B97A5" style={[styles.input, styles.textarea]} textAlignVertical="top" />
    <FormLabel label="File hash and chain-of-custody note" /><TextInput value={fileHash} onChangeText={setFileHash} placeholder="Hash if known; leave blank if not calculated" placeholderTextColor="#8B97A5" style={styles.input} /><TextInput value={chainOfCustody} onChangeText={setChainOfCustody} multiline placeholder="How the record was obtained, handled, or preserved" placeholderTextColor="#8B97A5" style={[styles.input, styles.textarea]} textAlignVertical="top" />
    <FormLabel label="Reliability, authentication, or discrepancy review" /><TextInput value={reliabilityConcerns} onChangeText={setReliabilityConcerns} multiline placeholder="Reliability concern, if any" placeholderTextColor="#8B97A5" style={[styles.input, styles.textareaShort]} textAlignVertical="top" /><TextInput value={authenticationQuestions} onChangeText={setAuthenticationQuestions} multiline placeholder="Authentication or completeness question, if any" placeholderTextColor="#8B97A5" style={[styles.input, styles.textareaShort]} textAlignVertical="top" /><TextInput value={potentialDiscrepancy} onChangeText={setPotentialDiscrepancy} multiline placeholder="Potential discrepancy requiring review — do not state as fact" placeholderTextColor="#8B97A5" style={[styles.input, styles.textareaShort]} textAlignVertical="top" />
    <FormLabel label="Next review action" /><TextInput value={nextAction} onChangeText={setNextAction} multiline placeholder="Example: Compare the original report with the dispatch log and retain source locations." placeholderTextColor="#8B97A5" style={[styles.input, styles.textarea]} textAlignVertical="top" />
    <TouchableOpacity onPress={save} activeOpacity={0.8} style={styles.saveButton}><Text style={styles.saveText}>Save local evidence item</Text><MaterialIcons name="check" size={19} color={colors.white} /></TouchableOpacity>
  </ScrollView></ScreenContainer>;
}

function TopBar({ title, onBack }: { title: string; onBack: () => void }) { return <View style={styles.topRow}><TouchableOpacity onPress={onBack} style={styles.backButton} activeOpacity={0.7}><MaterialIcons name="arrow-back" size={21} color={colors.navy} /></TouchableOpacity><Text style={styles.topTitle}>{title}</Text><View style={styles.topSpacer} /></View>; }
function FormLabel({ label, hint, required }: { label: string; hint?: string; required?: boolean }) { return <View style={styles.labelRow}><Text style={styles.label}>{label}{required ? <Text style={styles.required}> *</Text> : null}</Text>{hint ? <Text style={styles.hint}>{hint}</Text> : null}</View>; }
function Selector<T extends string>({ items, value, onChange }: { items: T[]; value: T; onChange: (next: T) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.selectorRow}>{items.map((item) => { const active = item === value; return <TouchableOpacity key={item} onPress={() => onChange(item)} activeOpacity={0.76} style={[styles.selector, active && styles.selectorActive]}><Text style={[styles.selectorText, active && styles.selectorTextActive]}>{item.replaceAll("_", " ")}</Text></TouchableOpacity>; })}</ScrollView>; }
const styles = StyleSheet.create({ container: { backgroundColor: colors.paper }, content: { padding: 20, paddingBottom: 34, gap: 10 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }, backButton: { width: 39, height: 39, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, justifyContent: "center", alignItems: "center" }, topTitle: { color: colors.navy, fontSize: 14, fontWeight: "800" }, topSpacer: { width: 39 }, title: { color: colors.charcoal, fontSize: 26, lineHeight: 32, letterSpacing: -0.5, fontWeight: "800", marginTop: 8 }, subtitle: { color: colors.slate, fontSize: 13, lineHeight: 19, marginBottom: 5 }, labelRow: { gap: 2, marginTop: 9 }, label: { color: colors.charcoal, fontSize: 13, fontWeight: "800" }, required: { color: colors.red }, hint: { color: colors.slate, fontSize: 11, lineHeight: 15 }, selectorRow: { paddingRight: 20, gap: 8 }, selector: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white }, selectorActive: { backgroundColor: colors.navy, borderColor: colors.navy }, selectorText: { color: colors.slate, fontSize: 10, fontWeight: "800" }, selectorTextActive: { color: colors.white }, input: { minHeight: 47, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, color: colors.charcoal, paddingHorizontal: 13, paddingVertical: 12, fontSize: 13, lineHeight: 18 }, textarea: { minHeight: 88 }, textareaShort: { minHeight: 66 }, row: { flexDirection: "row", gap: 9 }, half: { flex: 1 }, saveButton: { minHeight: 52, marginTop: 12, borderRadius: 16, backgroundColor: colors.navy, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 8 }, saveText: { color: colors.white, fontSize: 14, fontWeight: "800" } });
