import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { DisclosureBanner, colors } from "@/components/case-ui";
import { ScreenContainer } from "@/components/screen-container";
import { Priority, discoveryCategories, useCaseData } from "@/lib/case-store";

export default function DiscoveryChecklistScreen() {
  const router = useRouter(); const { addDiscovery } = useCaseData(); const [category, setCategory] = useState(discoveryCategories[0]); const [title, setTitle] = useState(""); const [custodian, setCustodian] = useState(""); const [question, setQuestion] = useState(""); const [priority, setPriority] = useState<Priority>("Medium");
  function addItem() { if (!title.trim() || !question.trim()) { Alert.alert("Add a title and question", "Describe the expected category and the question the original record could help you review."); return; } addDiscovery({ title: title.trim(), category, question: question.trim(), custodian: custodian.trim() || "Custodian not recorded", handlingNote: "Expected item not yet located in the case workspace. Preserve original material, metadata, and full context if received.", priority, state: "EXPECTED", requestDate: "", receivedDate: "", reviewDate: "", requestReference: "", followUp: "" }); router.back(); }
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.topRow}><TouchableOpacity onPress={() => router.back()} style={styles.backButton}><MaterialIcons name="arrow-back" size={21} color={colors.navy} /></TouchableOpacity><Text style={styles.topTitle}>Expected material</Text><View style={styles.topSpacer} /></View><Text style={styles.title}>Add a discovery review item.</Text><Text style={styles.subtitle}>Use this list to track material you expect to obtain, verify, or review. It does not make a claim about the item’s existence, contents, or production history.</Text><DisclosureBanner compact /><Text style={styles.label}>Evidence category</Text><View style={styles.chips}>{discoveryCategories.map((item) => <TouchableOpacity key={item} onPress={() => setCategory(item)} activeOpacity={0.75} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></TouchableOpacity>)}</View><Text style={styles.label}>Item title</Text><TextInput value={title} onChangeText={setTitle} placeholder="Example: Dispatch audio for incident date" placeholderTextColor="#8B97A5" style={styles.input} /><Text style={styles.label}>Custodian or source to contact</Text><TextInput value={custodian} onChangeText={setCustodian} placeholder="Agency, records office, court, or other custodian" placeholderTextColor="#8B97A5" style={styles.input} /><Text style={styles.label}>Neutral question this item could help review</Text><TextInput value={question} onChangeText={setQuestion} multiline placeholder="Example: What original audio or log documents the reported dispatch time?" placeholderTextColor="#8B97A5" style={[styles.input, styles.textarea]} textAlignVertical="top" /><Text style={styles.label}>Priority</Text><View style={styles.priorityRow}>{(["Critical", "High", "Medium", "Low"] as Priority[]).map((item) => <TouchableOpacity key={item} onPress={() => setPriority(item)} style={[styles.priorityChip, priority === item && styles.priorityChipActive]}><Text style={[styles.priorityText, priority === item && styles.priorityTextActive]}>{item}</Text></TouchableOpacity>)}</View><View style={styles.notice}><MaterialIcons name="find-in-page" size={19} color={colors.gold} /><Text style={styles.noticeText}>New items begin as <Text style={styles.noticeStrong}>Expected</Text>. Advance them only as you request, receive, and review actual material.</Text></View><TouchableOpacity onPress={addItem} activeOpacity={0.8} style={styles.saveButton}><Text style={styles.saveText}>Add expected item</Text><MaterialIcons name="playlist-add-check" size={19} color={colors.white} /></TouchableOpacity></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ container: { backgroundColor: colors.paper }, content: { padding: 20, paddingBottom: 34, gap: 11 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 5 }, backButton: { width: 39, height: 39, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, justifyContent: "center", alignItems: "center" }, topTitle: { color: colors.navy, fontSize: 14, fontWeight: "800" }, topSpacer: { width: 39 }, title: { color: colors.charcoal, fontSize: 25, lineHeight: 31, letterSpacing: -0.4, fontWeight: "800", marginTop: 6 }, subtitle: { color: colors.slate, fontSize: 13, lineHeight: 19 }, label: { marginTop: 8, color: colors.charcoal, fontSize: 13, fontWeight: "800" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1 }, chipActive: { backgroundColor: colors.navy, borderColor: colors.navy }, chipText: { color: colors.slate, fontSize: 10, fontWeight: "800" }, chipTextActive: { color: colors.white }, input: { minHeight: 47, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, color: colors.charcoal, paddingHorizontal: 13, paddingVertical: 12, fontSize: 13, lineHeight: 18 }, textarea: { minHeight: 88 }, priorityRow: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, priorityChip: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 999, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1 }, priorityChipActive: { backgroundColor: colors.navy, borderColor: colors.navy }, priorityText: { color: colors.slate, fontSize: 10, fontWeight: "800" }, priorityTextActive: { color: colors.white }, notice: { flexDirection: "row", gap: 8, backgroundColor: "#FFF1D6", borderWidth: 1, borderColor: "#F0D19D", borderRadius: 14, padding: 12, alignItems: "flex-start", marginTop: 3 }, noticeText: { flex: 1, color: colors.gold, fontSize: 12, lineHeight: 17, fontWeight: "700" }, noticeStrong: { fontWeight: "900" }, saveButton: { minHeight: 52, borderRadius: 16, backgroundColor: colors.navy, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 8, marginTop: 4 }, saveText: { color: colors.white, fontSize: 14, fontWeight: "800" } });
