import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Clipboard from "expo-clipboard";
import { useRouter } from "expo-router";
import { Alert, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";

import { DisclosureBanner, colors } from "@/components/case-ui";
import { ScreenContainer } from "@/components/screen-container";
import { getWorkspaceExport, useCaseData } from "@/lib/case-store";
import { authenticateWorkspace } from "@/lib/session-protection";

export default function PrivacyScreen() {
  const router = useRouter(); const { biometricGateEnabled, setBiometricGateEnabled, clearCaseData, localOnly } = useCaseData();
  async function toggleBiometric(next: boolean) {
    if (!next) { setBiometricGateEnabled(false); return; }
    const result = await authenticateWorkspace("Enable Pro Se Compass workspace protection");
    if (result.success) { setBiometricGateEnabled(true); Alert.alert("Device protection enabled", "Pro Se Compass will ask for device authentication when the app returns after one minute in the background. This does not encrypt your case data at rest."); }
    else Alert.alert("Protection not enabled", result.message || "The device could not complete biometric or passcode authentication.");
  }
  async function exportData() { try { await Clipboard.setStringAsync(getWorkspaceExport()); Alert.alert("Local workspace export copied", "A JSON copy of the current Pro Se Compass workspace is on your clipboard. Treat it as sensitive and paste or save it only where you intend to share it."); } catch { Alert.alert("Export not copied", "Clipboard access was unavailable. Try again from a device or browser that permits clipboard use."); } }
  function clearData() { Alert.alert("Clear this local workspace?", "This overwrites the current local workspace with fictional demo data in this app. This does not guarantee forensic deletion from device backups or operating-system storage.", [{ text: "Cancel", style: "cancel" }, { text: "Clear local workspace", style: "destructive", onPress: () => { clearCaseData(); Alert.alert("Local workspace cleared", "The app now contains only its fictional demo workspace."); } }]); }
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.container}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.topRow}><TouchableOpacity onPress={() => router.back()} style={styles.backButton}><MaterialIcons name="arrow-back" size={21} color={colors.navy} /></TouchableOpacity><Text style={styles.topTitle}>Privacy controls</Text><View style={styles.topSpacer} /></View><View style={styles.heroIcon}><MaterialIcons name="shield" size={27} color={colors.navy} /></View><Text style={styles.title}>Your workspace stays local by default.</Text><Text style={styles.subtitle}>Pro Se Compass Phase 2 does not send case records to a cloud service, account, search provider, or remote model. The controls below give you a visible way to export or clear local workspace data.</Text><DisclosureBanner compact />
    <Section title="Local-only mode"><View style={styles.row}><View style={styles.rowTextBox}><Text style={styles.rowTitle}>Case content stays on this device</Text><Text style={styles.rowBody}>{localOnly ? "Enabled in this Phase 2 build." : "Not available in this build."}</Text></View><View style={styles.lockedPill}><Text style={styles.lockedText}>ON</Text></View></View><Text style={styles.notice}>Cloud sync, uploads, OCR, external court-data access, and remote AI are not enabled. Before any are added, the app needs explicit data-transmission consent, security design, deletion controls, and a privacy review.</Text></Section>
    <Section title="Device re-authentication"><View style={styles.row}><View style={styles.rowTextBox}><Text style={styles.rowTitle}>Require device authentication after backgrounding</Text><Text style={styles.rowBody}>Available on supported iOS and Android devices after the workspace is in the background for one minute. Device passcode fallback is allowed.</Text></View><Switch value={biometricGateEnabled} onValueChange={toggleBiometric} trackColor={{ false: "#D7DEE7", true: "#7CA4C6" }} thumbColor={biometricGateEnabled ? colors.navy : "#FFFFFF"} /></View><Text style={styles.notice}>This is a session gate, not a claim of encrypted case-file storage. It is unavailable on the web version and requires a development or production build for Face ID testing.</Text></Section>
    <Section title="Data ownership and export"><TouchableOpacity onPress={exportData} activeOpacity={0.78} style={styles.actionButton}><MaterialIcons name="content-copy" size={19} color={colors.navy} /><View style={styles.actionTextBox}><Text style={styles.actionTitle}>Copy workspace JSON export</Text><Text style={styles.actionBody}>Creates a local text export for you to paste into a location you control.</Text></View><MaterialIcons name="chevron-right" size={20} color={colors.slate} /></TouchableOpacity><TouchableOpacity onPress={clearData} activeOpacity={0.78} style={styles.destructiveButton}><MaterialIcons name="delete-outline" size={19} color={colors.red} /><View style={styles.actionTextBox}><Text style={styles.destructiveTitle}>Clear this local workspace</Text><Text style={styles.destructiveBody}>Overwrites current app workspace data after confirmation; it is not forensic secure deletion.</Text></View><MaterialIcons name="chevron-right" size={20} color={colors.red} /></TouchableOpacity></Section>
    <View style={styles.footerNotice}><MaterialIcons name="info-outline" size={18} color={colors.slate} /><Text style={styles.footerText}>Before using real case material in any future synced or document-storage release, obtain an independent security and privacy review. Redact unnecessary personal identifiers before sharing an export.</Text></View>
  </ScrollView></ScreenContainer>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ container: { backgroundColor: colors.paper }, content: { padding: 20, paddingBottom: 34, gap: 13 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }, backButton: { width: 39, height: 39, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, justifyContent: "center", alignItems: "center" }, topTitle: { color: colors.navy, fontSize: 14, fontWeight: "800" }, topSpacer: { width: 39 }, heroIcon: { width: 52, height: 52, borderRadius: 17, justifyContent: "center", alignItems: "center", backgroundColor: colors.blue, marginTop: 5 }, title: { color: colors.charcoal, fontSize: 25, lineHeight: 31, letterSpacing: -0.4, fontWeight: "800" }, subtitle: { color: colors.slate, fontSize: 13, lineHeight: 19 }, section: { backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 17, padding: 13, gap: 11 }, sectionTitle: { color: colors.charcoal, fontSize: 15, fontWeight: "800" }, row: { flexDirection: "row", gap: 10, alignItems: "center" }, rowTextBox: { flex: 1 }, rowTitle: { color: colors.charcoal, fontSize: 13, lineHeight: 18, fontWeight: "800" }, rowBody: { color: colors.slate, fontSize: 11, lineHeight: 16, marginTop: 2 }, lockedPill: { backgroundColor: "#DDF4EE", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 }, lockedText: { color: colors.teal, fontSize: 10, fontWeight: "900", letterSpacing: 0.5 }, notice: { color: colors.slate, fontSize: 11, lineHeight: 16, backgroundColor: "#F2F5F7", padding: 9, borderRadius: 10 }, actionButton: { flexDirection: "row", gap: 9, alignItems: "center", backgroundColor: colors.blue, borderRadius: 13, padding: 11 }, destructiveButton: { flexDirection: "row", gap: 9, alignItems: "center", backgroundColor: "#FCE9E7", borderRadius: 13, padding: 11 }, actionTextBox: { flex: 1 }, actionTitle: { color: colors.navy, fontSize: 12, fontWeight: "800" }, actionBody: { color: colors.navy, fontSize: 10, lineHeight: 15, marginTop: 2 }, destructiveTitle: { color: colors.red, fontSize: 12, fontWeight: "800" }, destructiveBody: { color: colors.red, fontSize: 10, lineHeight: 15, marginTop: 2 }, footerNotice: { flexDirection: "row", gap: 8, alignItems: "flex-start", padding: 8 }, footerText: { flex: 1, color: colors.slate, fontSize: 11, lineHeight: 16 } });
